<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-UOTE3Q5R" ignored="0" name="t2" tests="5" failures="3" timestamp="2020-11-11T11:22:39 CST" time="0.037" errors="0">
  <testcase name="test1" time="0.006" classname="com.webtest.demo.Demo"/>
  <testcase name="test2" time="0.001" classname="com.webtest.demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at com.webtest.demo.Demo.test2(Demo.java:18)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase name="test3" time="0.001" classname="com.webtest.demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [1] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [3]
at com.webtest.demo.Demo.test3(Demo.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase name="test4" time="0.001" classname="com.webtest.demo.Demo"/>
  <testcase name="test5" time="0.0" classname="com.webtest.demo.Demo">
    <failure type="java.lang.AssertionError" message="expected [1] but found [4]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [4]
at com.webtest.demo.Demo.test5(Demo.java:30)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
</testsuite> <!-- t2 -->
